spring.application.name=airline

# Show full error details
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.timeout=5000


# ??? Server ???????????????????????????????????????????????????
server.port=8080
app.base-url=http://localhost:8080

# ??? MySQL DataSource ??????????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/airline_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ??? JPA / Hibernate ??????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ??? JWT ??????????????????????????????????????????????????????
jwt.secret=
jwt.expiration=86400000 

# ??? Swagger / OpenAPI ????????????????????????????????????????
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ??? Logging ??????????????????????????????????????????????????
logging.level.com.airline=DEBUG
logging.level.org.springframework.security=DEBUG
