spring.application.name=demo
#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/airline_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
#server.port=9090

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.security.user.name=user
spring.security.user.password=user
jwt.secretKey="afeoiwrow3h8rhfowiaho3fhao8w3hr89afhwo8hzfoeh0wh3oliawsje"


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhaveshgupta09876@gmail.com
spring.mail.password=trxi bhrc fkle cfst
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

